package modelo.hibernate;
// Generated 13-ene-2014 23:25:12 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Emple generated by hbm2java
 */
public class Emple  implements java.io.Serializable {


     private short empNo;
     private Depart depart;
     private String apellido;
     private String oficio;
     private Short dir;
     private Date fechaAlt;
     private Integer salario;
     private Integer comision;

    public Emple() {
    }

	
    public Emple(short empNo, Depart depart) {
        this.empNo = empNo;
        this.depart = depart;
    }
    public Emple(short empNo, Depart depart, String apellido, String oficio, 
            Short dir, Date fechaAlt, Integer salario, Integer comision) {
       this.empNo = empNo;
       this.depart = depart;
       this.apellido = apellido;
       this.oficio = oficio;
       this.dir = dir;
       this.fechaAlt = fechaAlt;
       this.salario = salario;
       this.comision = comision;
    }
   
    public short getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(short empNo) {
        this.empNo = empNo;
    }
    public Depart getDepart() {
        return this.depart;
    }
    
    public void setDepart(Depart depart) {
        this.depart = depart;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public Short getDir() {
        return this.dir;
    }
    
    public void setDir(Short dir) {
        this.dir = dir;
    }
    public Date getFechaAlt() {
        return this.fechaAlt;
    }
    
    public void setFechaAlt(Date fechaAlt) {
        this.fechaAlt = fechaAlt;
    }
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }
    public Integer getComision() {
        return this.comision;
    }
    
    public void setComision(Integer comision) {
        this.comision = comision;
    }

    @Override
    public String toString() {
        return apellido;
    }

}


