-- *********** METODOS DEPARTAMENTOS **********

CREATE OR REPLACE FUNCTION findDepart(cod DEPART.DEPT_NO%TYPE) 
RETURN DEPARTVO IS
	
	codDep NUMBER;
	nombre VARCHAR2(14);
	loc VARCHAR2(14);
	v_depart DEPARTVO;
BEGIN 
	SELECT DEPT_NO, DNOMBRE, LOC into codDep, nombre, loc
	FROM DEPART
	WHERE DEPT_NO = cod;

	v_depart := DEPARTVO(codDep, nombre, loc);

	RETURN v_depart;
END;
/


CREATE OR REPLACE FUNCTION existDepart(cod DEPART.DEPT_NO%TYPE)
RETURN NUMBER IS
	
	numDep NUMBER;
BEGIN 
	SELECT COUNT(*) INTO numDep
	FROM DEPART 
	WHERE DEPT_NO = cod;

	return numDep;
END;
/

CREATE OR REPLACE FUNCTION nombreDep (codDep DEPART.DEPT_NO%TYPE) RETURN BOOLEAN IS
		cont NUMBER;
	BEGIN 
		SELECT COUNT(*) INTO cont
		FROM DEPART
		WHERE DEPT_NO=codDep;

		IF cont=0 THEN
			RETURN FALSE;
		ELSE
			RETURN TRUE;
		END IF;
END nombreDep;
/

--Borra un departamento con empleados y sus empleados los traspasa a otro empleado existente
CREATE OR REPLACE FUNCTION borra_dep(
	codDepDelete DEPART.DEPT_NO%TYPE,
	codNewDep DEPART.DEPT_NO%TYPE) RETURN NUMBER IS 
	BEGIN 
		IF nombreDep(codDepDelete) THEN
			IF nombreDep(codNewDep) THEN
				UPDATE EMPLE 
				SET DEPT_NO=codNewDep
				WHERE DEPT_NO=codDepDelete;

				DELETE FROM DEPART
				WHERE DEPT_NO=codDepDelete;

				RETURN 1;
			ELSE
				RAISE_APPLICATION_ERROR(-20001, 'El departamento a donde se quiere trasladar los empleados no existe');
			END IF;
		ELSE
			RAISE_APPLICATION_ERROR(-20001, 'El codigo de departamento es erroneo.');
		END IF;
END borra_dep;
/


-- *********** METODOS EMPLEADOS **********

CREATE OR REPLACE FUNCTION existEmple(cod EMPLE.EMP_NO%TYPE)
RETURN NUMBER IS
	
	numEmple NUMBER;
BEGIN 
	SELECT COUNT(*) INTO numEmple
	FROM EMPLE
	WHERE EMP_NO= cod;

	return numEmple;
END;
/

CREATE OR REPLACE FUNCTION nuevoCodigo
RETURN NUMBER IS

	cod NUMBER;
BEGIN
	SELECT MAX(EMP_NO) INTO cod
	FROM EMPLE;

	RETURN cod + 10;
END;
/

CREATE OR REPLACE PROCEDURE newCodigo IS

	cod NUMBER;
BEGIN
	SELECT MAX(EMP_NO) INTO cod
	FROM EMPLE;
	
	cod := cod + 10;
	
	DBMS_OUTPUT.PUT_LINE(cod);
END;
/

REM ******** TABLA DEPART: ***********

DROP TABLE DEPART cascade constraints; 

CREATE TABLE DEPART (
 DEPT_NO  NUMBER(2) CONSTRAINT DEP_COD_NN NOT NULL,
 DNOMBRE  VARCHAR2(14) CONSTRAINT DEP_NOM_NN NOT NULL, 
 LOC      VARCHAR2(14),
 CONSTRAINT DEP_COD_PK PRIMARY KEY (DEPT_NO)
 );

INSERT INTO DEPART VALUES (10,'CONTABILIDAD','SEVILLA');
INSERT INTO DEPART VALUES (20,'INVESTIGACION','MADRID');
INSERT INTO DEPART VALUES (30,'VENTAS','BARCELONA');
INSERT INTO DEPART VALUES (40,'PRODUCCION','BILBAO');
COMMIT;


REM ******** TABLA EMPLE: *************

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

DROP TABLE EMPLE cascade constraints; 

CREATE TABLE EMPLE (
 EMP_NO    NUMBER(4) CONSTRAINT EMP_COD_NN NOT NULL,
 APELLIDO  VARCHAR2(10) ,
 OFICIO    VARCHAR2(10) ,
 DIR       NUMBER(4),
 FECHA_ALT DATE      ,
 SALARIO   NUMBER(7),
 COMISION  NUMBER(7),
 DEPT_NO   NUMBER(2) CONSTRAINT EMP_DEP_NN NOT NULL,
 CONSTRAINT EMP_COD_PK PRIMARY KEY (EMP_NO),
 CONSTRAINT EMP_DEP_FK FOREIGN KEY (DEPT_NO) REFERENCES DEPART(DEPT_NO)
 );

INSERT INTO EMPLE VALUES (7369,'SANCHEZ','EMPLEADO',7902,'17/12/1990',
                        1040,NULL,20);
INSERT INTO EMPLE VALUES (7499,'ARROYO','VENDEDOR',7698,'20/02/1990',
                        1500,390,30);
INSERT INTO EMPLE VALUES (7521,'SALA','VENDEDOR',7698,'22/02/1991',
                        1625,650,30);
INSERT INTO EMPLE VALUES (7566,'JIMENEZ','DIRECTOR',7839,'02/04/1991',
                        2900,NULL,20);
INSERT INTO EMPLE VALUES (7654,'MARTIN','VENDEDOR',7698,'29/09/1991',
                        1600,1020,30);
INSERT INTO EMPLE VALUES (7698,'NEGRO','DIRECTOR',7839,'01/05/1991',
                        3005,NULL,30);
INSERT INTO EMPLE VALUES (7782,'CEREZO','DIRECTOR',7839,'09/06/1991',
                        2885,NULL,10);
INSERT INTO EMPLE VALUES (7788,'GIL','ANALISTA',7566,'09/11/1991',
                        3000,NULL,20);
INSERT INTO EMPLE VALUES (7839,'REY','PRESIDENTE',NULL,'17/11/1991',
                        4100,NULL,10);
INSERT INTO EMPLE VALUES (7844,'TOVAR','VENDEDOR',7698,'08/09/1991',
                        1350,0,30);
INSERT INTO EMPLE VALUES (7876,'ALONSO','EMPLEADO',7788,'23/09/1991',
                        1430,NULL,20);
INSERT INTO EMPLE VALUES (7900,'JIMENO','EMPLEADO',7698,'03/12/1991',
                        1335,NULL,30);
INSERT INTO EMPLE VALUES (7902,'FERNANDEZ','ANALISTA',7566,'03/12/1991',
                        3000,NULL,20);
INSERT INTO EMPLE VALUES (7934,'MUÑOZ','EMPLEADO',7782,'23/01/1992',
                        1690,NULL,10);

COMMIT;